#!/usr/bin/env zsh

VSCODE_EXTENSIONS=(
  1password.op-vscode
  aaron-bond.better-comments
  adpyke.vscode-userscript
  antfu.icons-carbon
  antfu.open-in-github-button
  apollographql.vscode-apollo
  artdiniz.quitcontrol-vscode
  asciidoctor.asciidoctor-vscode
  bierner.comment-tagged-templates
  bierner.folder-source-actions
  bierner.github-markdown-preview
  bierner.markdown-checkbox
  bierner.markdown-emoji
  bierner.markdown-footnotes
  bierner.markdown-mermaid
  bierner.markdown-preview-github-styles
  bierner.markdown-yaml-preamble
  boyswan.glsl-literal
  bpruitt-goddard.mermaid-markdown-syntax-highlighting
  bradlc.vscode-tailwindcss
  bufbuild.vscode-buf
  chenglou92.rescript-vscode
  christian-kohler.path-intellisense
  codezombiech.gitignore
  dakara.transformer
  davidanson.vscode-markdownlint
  dbaeumer.vscode-eslint
  denoland.vscode-deno
  divlo.vscode-styled-jsx-languageserver
  drknoxy.eslint-disable-snippets
  eamodio.gitlens
  editorconfig.editorconfig
  esbenp.prettier-vscode
  fabiospampinato.vscode-open-in-github
  foxundermoon.shell-format
  github.codespaces
  github.copilot
  github.copilot-chat
  github.github-vscode-theme
  github.remotehub
  github.vscode-github-actions
  github.vscode-pull-request-github
  golang.go
  graphql.vscode-graphql
  graphql.vscode-graphql-execution
  graphql.vscode-graphql-syntax
  jock.svg
  josee9988.minifyall
  mddanishyusuf.iconbuddy-vs-code-plugin
  mikestead.dotenv
  ms-azuretools.vscode-docker
  ms-python.debugpy
  ms-python.python
  ms-python.vscode-pylance
  ms-vscode-remote.remote-ssh
  ms-vscode-remote.remote-ssh-edit
  ms-vscode.cmake-tools
  ms-vscode.cpptools
  ms-vscode.makefile-tools
  ms-vscode.remote-explorer
  ms-vscode.remote-repositories
  ms-vscode.remote-server
  ms-vsliveshare.vsliveshare
  mylesmurphy.prettify-ts
  naumovs.color-highlight
  orta.vscode-twoslash-queries
  pbkit.vscode-pbkit
  prisma.prisma
  pustelto.bracketeer
  pveyes.aperture
  redhat.vscode-commons
  redhat.vscode-xml
  redhat.vscode-yaml
  richie5um2.vscode-sort-json
  rust-lang.rust-analyzer
  sanity-io.vscode-sanity
  sburg.vscode-javascript-booster
  slevesque.shader
  sourcegraph.cody-ai
  styled-components.vscode-styled-components
  tamasfe.even-better-toml
  tauri-apps.tauri-vscode
  tldraw-org.tldraw-vscode
  twxs.cmake
  unifiedjs.vscode-mdx
  vunguyentuan.vscode-postcss
  wallabyjs.quokka-vscode
  wmaurer.change-case
  yoavbls.pretty-ts-errors
  yunduo.color-highlight-css-color-4
  yzhang.markdown-all-in-one
  zachhardesty.convert-object-to-jsx-vscode
  zengxingxin.sort-js-object-keys
)
echo "Installing vscode extensions..." &&
  for EXTENSION in $VSCODE_EXTENSIONS; do
    code --install-extension $EXTENSION --force
  done

echo "Done! ✨"
