#!/usr/bin/env zsh

VSCODE_EXTENSIONS=(
  1Password.op-vscode
  aaron-bond.better-comments
  ahmadalli.vscode-nginx-conf
  antfu.open-in-github-button
  apollographql.vscode-apollo
  artdiniz.quitcontrol-vscode
  asciidoctor.asciidoctor-vscode
  astro-build.astro-vscode
  bierner.comment-tagged-templates
  bierner.folder-source-actions
  bierner.github-markdown-preview
  bierner.markdown-checkbox
  bierner.markdown-emoji
  bierner.markdown-footnotes
  bierner.markdown-mermaid
  bierner.markdown-preview-github-styles
  bierner.markdown-yaml-preamble
  bradlc.vscode-tailwindcss
  bufbuild.vscode-buf
  chenglou92.rescript-vscode
  christian-kohler.path-intellisense
  codezombiech.gitignore
  dakara.transformer
  DavidAnson.vscode-markdownlint
  davidbwaters.macos-modern-theme
  dbaeumer.vscode-eslint
  denoland.vscode-deno
  drKnoxy.eslint-disable-snippets
  eamodio.gitlens
  EditorConfig.EditorConfig
  esbenp.prettier-vscode
  fabiospampinato.vscode-open-in-github
  figma.figma-vscode-extension
  foxundermoon.shell-format
  GitHub.codespaces
  GitHub.copilot
  GitHub.copilot-chat
  GitHub.github-vscode-theme
  golang.go
  GraphQL.vscode-graphql
  GraphQL.vscode-graphql-execution
  GraphQL.vscode-graphql-syntax
  jock.svg
  miguelsolorio.min-theme
  mikestead.dotenv
  monokai.theme-monokai-pro-vscode
  ms-azuretools.vscode-docker
  ms-python.python
  ms-python.vscode-pylance
  ms-vscode-remote.remote-ssh
  ms-vscode-remote.remote-ssh-edit
  ms-vscode.cmake-tools
  ms-vscode.cpptools
  ms-vscode.makefile-tools
  ms-vscode.remote-explorer
  ms-vscode.remote-server
  ms-vsliveshare.vsliveshare
  naumovs.color-highlight
  Orta.vscode-twoslash-queries
  pbkit.vscode-pbkit
  Prisma.prisma
  pustelto.bracketeer
  redhat.vscode-commons
  redhat.vscode-xml
  redhat.vscode-yaml
  richie5um2.vscode-sort-json
  rust-lang.rust-analyzer
  sburg.vscode-javascript-booster
  styled-components.vscode-styled-components
  tamasfe.even-better-toml
  tldraw-org.tldraw-vscode
  twxs.cmake
  unifiedjs.vscode-mdx
  VisualStudioExptTeam.vscodeintellicode
  vunguyentuan.vscode-postcss
  WallabyJs.quokka-vscode
  wmaurer.change-case
  yzhang.markdown-all-in-one
  zachhardesty.convert-object-to-jsx-vscode
  zengxingxin.sort-js-object-keys
)
echo "Installing vscode extensions..." &&
  for EXTENSION in $VSCODE_EXTENSIONS; do
    code --install-extension $EXTENSION --force
  done

echo "Done! ✨"
